// fast_search3.cpp
// ---------------------------------------------------------------------------
// Memory-light version of the search (no global partner table).
//
// Same mathematics as fast_search.cpp / fast_search2.cpp (see their headers and
// notes/reduction.md), but the partner list of C,
//     T(C) = { A : 1 <= A <= N,  A^2 + C^2 is a perfect square },
// is generated from the factorisation of C instead of from a stored table:
//     A^2 + C^2 = hyp^2  <=>  (hyp-A)(hyp+A) = C^2,
// so with u = hyp-A, v = hyp+A we need u*v = C^2, u < C < v, u = v (mod 2),
// and then A = (v-u)/2.  Hence T(C) = { (v-u)/2 : u | C^2, u < C, u = C^2/u
// (mod 2) }, which is generated by a depth-first walk over the divisors of C^2
// (pruned at C).  Memory is O(divisors of C^2) instead of O(number of
// Pythagorean pairs <= N), so Q up to 1e9 becomes reachable; the price is
// sum_{C<=N} d(C^2) divisor-generation steps.
//
// The small prime factor sieve uses 2 bytes per entry: for C <= N the least
// prime factor of C is at most sqrt(N) < 65536, and 0 marks "C is prime".
//
// Build: g++ -O2 -march=native -fopenmp -std=c++17 -o fast_search3 fast_search3.cpp
// Run:   fast_search3 --N 1000000000
// ---------------------------------------------------------------------------

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cstdint>
#include <cmath>
#include <string>
#include <vector>
#include <algorithm>
#include <chrono>

#ifdef _OPENMP
#include <omp.h>
#endif

typedef uint32_t u32;
typedef uint64_t u64;
typedef uint16_t u16;

static inline bool isSquare(u64 n) {
    if (n == 0) return true;
    u64 r = (u64)sqrtl((long double)n);
    while (r > 0 && r * r > n) --r;
    while ((r + 1) * (r + 1) <= n) ++r;
    return r * r == n;
}

int main(int argc, char **argv) {
    u64 N = 1000000;
    bool useParity = true, useMod3 = false, threeCond = false, statsOnly = false;
    for (int i = 1; i < argc; ++i) {
        if (!strcmp(argv[i], "--N") && i + 1 < argc) N = strtoull(argv[++i], 0, 10);
        else if (!strcmp(argv[i], "--no-parity")) useParity = false;
        else if (!strcmp(argv[i], "--mod3")) useMod3 = true;
        else if (!strcmp(argv[i], "--three")) threeCond = true;
        else if (!strcmp(argv[i], "--stats")) statsOnly = true;
        else { fprintf(stderr, "unknown arg %s\n", argv[i]); return 2; }
    }
    auto t0 = std::chrono::steady_clock::now();

    // ---- least-prime-factor sieve, 2 bytes per entry, 0 = prime ----
    std::vector<u16> spf(N + 1, 0);
    for (u64 p = 2; p * p <= N; ++p)
        if (spf[p] == 0)
            for (u64 i = p * p; i <= N; i += p)
                if (spf[i] == 0) spf[i] = (u16)p;
    auto t1 = std::chrono::steady_clock::now();
    fprintf(stderr, "[sieve] N=%llu %.2fs\n", (unsigned long long)N,
            std::chrono::duration<double>(t1 - t0).count());

    std::vector<std::string> solutions;
    u64 candidates = 0, tested = 0, divisorSteps = 0, totalPartners = 0, maxPartners = 0;

#ifdef _OPENMP
    int nthreads = omp_get_max_threads();
#else
    int nthreads = 1;
#endif
    std::vector<std::vector<std::string>> local(nthreads);

#pragma omp parallel reduction(+:candidates,tested,divisorSteps,totalPartners)
    {
#ifdef _OPENMP
        int tid = omp_get_thread_num();
#else
        int tid = 0;
#endif
        std::vector<u64> primes, exps, powers;   // factorisation of C
        std::vector<u32> list;
        long long locMax = 0;
#pragma omp for schedule(dynamic, 512)
        for (long long Ci = 1; Ci <= (long long)N; ++Ci) {
            u64 C = (u64)Ci;
            // ---- factor C ----
            primes.clear(); exps.clear();
            u64 m = C;
            while (m > 1) {
                u64 p = spf[m] ? spf[m] : m;
                u64 e = 0;
                while (m % p == 0) { m /= p; ++e; }
                primes.push_back(p); exps.push_back(e);
            }
            // ---- divisors u of C^2 with u < C, same parity as C^2/u ----
            list.clear();
            u64 C2 = C * C;
            // depth-first over primes; count nodes for statistics
            struct Rec {
                const std::vector<u64> &primes, &exps;
                u64 C, C2, N;
                std::vector<u32> &list;
                u64 steps;
                void go(size_t idx, u64 cur) {
                    ++steps;
                    if (idx == primes.size()) {
                        if (cur < C) {                 // u < C  (A >= 1)
                            u64 v = C2 / cur;
                            if (((cur ^ v) & 1) == 0) {
                                u64 A = (v - cur) / 2;
                                if (A >= 1 && A <= N) list.push_back((u32)A);
                            }
                        }
                        return;
                    }
                    u64 pw = 1;
                    for (u64 j = 0; j <= 2 * exps[idx]; ++j) {
                        if (cur > C / pw) break;       // prune once cur*pw > C
                        go(idx + 1, cur * pw);
                        pw *= primes[idx];
                    }
                }
            } rec{primes, exps, C, C2, N, list, 0};
            rec.go(0, 1);
            divisorSteps += rec.steps;
            std::sort(list.begin(), list.end());
            totalPartners += list.size();
            if ((long long)list.size() > locMax) locMax = (long long)list.size();
            if (statsOnly) continue;

            // ---- pair loop over T(C) ----
            u64 k = list.size();
            for (u64 i = 0; i < k; ++i) {
                u32 A = list[i];
                for (u64 j = i + 1; j < k; ++j) {
                    u32 B = list[j];
                    u64 Q = (u64)A + B;
                    if (Q > N) break;
                    if (Q <= C) continue;          // D = Q - C <= 0
                    candidates++;
                    u32 D = (u32)(Q - C);
                    if (useParity) {
                        bool ok;
                        if ((A & 1) && (B & 1) && !((u32)C & 3) && !(D & 3)) ok = true;
                        else if (((u32)C & 1) && (D & 1) && !(A & 3) && !(B & 3)) ok = true;
                        else ok = false;
                        if (!ok) continue;
                    }
                    if (useMod3) {
                        if (!((A % 3 == 0 && B % 3 == 0) ||
                              (((u32)C % 3 == 0) && (D % 3 == 0)))) continue;
                    }
                    tested++;
                    bool okAD = isSquare((u64)A * A + (u64)D * D);
                    bool okBD = threeCond ? true : isSquare((u64)B * B + (u64)D * D);
                    if (okAD && okBD) {
                        char buf[160];
                        snprintf(buf, sizeof buf,
                                 "SOLUTION Q=%llu A=%u B=%u C=%u D=%u  (x=%llu/%llu,y=%u/%llu)",
                                 (unsigned long long)Q, A, B, (u32)C, D,
                                 (unsigned long long)A, (unsigned long long)Q,
                                 (u32)C, (unsigned long long)Q);
                        local[tid].push_back(buf);
                    }
                }
            }
        }
#pragma omp critical
        if (locMax > maxPartners) maxPartners = (u64)locMax;
    }
    for (int t = 0; t < nthreads; ++t)
        for (auto &s : local[t]) solutions.push_back(s);

    auto t2 = std::chrono::steady_clock::now();
    printf("N=%llu divisor_steps=%llu partners=%llu max_partners_per_C=%llu "
           "candidates=%llu tested=%llu solutions=%zu\n",
           (unsigned long long)N, (unsigned long long)divisorSteps,
           (unsigned long long)totalPartners, (unsigned long long)maxPartners,
           (unsigned long long)candidates, (unsigned long long)tested, solutions.size());
    for (auto &s : solutions) printf("%s\n", s.c_str());
    fflush(stdout);
    fprintf(stderr, "[search] %.2fs total %.2fs threads=%d parity=%s mod3=%s\n",
            std::chrono::duration<double>(t2 - t1).count(),
            std::chrono::duration<double>(t2 - t0).count(), nthreads,
            useParity ? "on" : "off", useMod3 ? "on" : "off");
    return 0;
}
